const UserTypes = {
    ADD_PROJECT: 'ADD_PROJECT',
    ADD_PROJECT_LOADING: 'ADD_PROJECT_LOADING',
    ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',
    ADD_PROJECT_ERROR: 'ADD_PROJECT_ERROR',
    ADD_PROJECT_RESET: 'ADD_PROJECT_RESET',

    // get Catergory
    GET_USERS: "GET_USERS",
    GET_USERS_LOADING: "GET_USERS_LOADING",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_RESET: "GET_USERS_RESET",
    GET_USERS_ERROR: "GET_USERS_ERROR",

    // update project details

    UPDATE_PROJECT_DETAILS: "UPDATE_PROJECT_DETAILS",
    UPDATE_PROJECT_DETAILS_LOADING: "UPDATE_PROJECT_DETAILS_LOADING",
    UPDATE_PROJECT_DETAILS_SUCCESS: "UPDATE_PROJECT_DETAILS_SUCCESS",   
    UPDATE_PROJECT_DETAILS_ERROR: "UPDATE_PROJECT_DETAILS_ERROR",
    UPDATE_PROJECT_DETAILS_RESET: "UPDATE_PROJECT_DETAILS_RESET",
    
        // delete project

        DELETE_PROJECT_DETAILS: "DELETE_PROJECT_DETAILS",
        DELETE_PROJECT_DETAILS_LOADING: "DELETE_PROJECT_DETAILS_LOADING",
        DELETE_PROJECT_DETAILS_SUCCESS: "DELETE_PROJECT_DETAILS_SUCCESS",   
        DELETE_PROJECT_DETAILS_ERROR: "DELETE_PROJECT_DETAILS_ERROR",
        DELETE_PROJECT_DETAILS_RESET: "DELETE_PROJECT_DETAILS_RESET",
        // get orojectById
        GET_PROJECT_BY_ID: "GET_PROJECT_BY_ID",
        GET_PROJECT_BY_ID_LOADING: "GET_PROJECT_BY_ID_LOADING",
        GET_PROJECT_BY_ID_SUCCESS: "GET_PROJECT_BY_ID_SUCCESS",
        GET_PROJECT_BY_ID_RESET: "GET_PROJECT_BY_ID_RESET",
        GET_PROJECT_BY_ID_ERROR: "GET_PROJECT_BY_ID_ERROR",
    
};

export default UserTypes;
